# NOTE: If you want the data to persist, before you run docker-compose you need to add the following volume:
##  docker volume create --name=pgdata

# Other wise all data added and modified to the database will be removed upon stopping the container

# Command to build:
#   docker-compose up -d

# Command to stop:
#   docker-compose down

version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: example
      POSTGRES_DB: game
    volumes:
      - bvc:/var/lib/postgresql/data
      - ./bvc.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5422:5432

volumes:
  bvc:
    external: true
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
