version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: example
      POSTGRES_DB: game
    volumes:
      - minesweeper:/var/lib/postgresql/data
      - ./game.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

volumes:
  minesweeper:
    external: true
